#!/usr/bin/env python3
"""Regenerate a board's task indexes inside their delimited blocks.

    scripts/generate_index.py --board .scratch/task_board
    scripts/generate_index.py --board .scratch/task_board --check

Writes several generated regions, each for a different reader:

  README.md    live work -- everything still in play, plus revisit/, grouped by
               status. Completed and superseded appear only as a count and a
               pointer, so the file a person opens daily does not grow unbounded.
  ARCHIVE.md   the full history, grouped by month, each entry carrying the
               task's one-line `outcome`.
  TREE.md      the composition view: specs and their tickets and subtickets
               nested, regardless of status. Created only when the board has
               composition. Where README groups by status, this groups by
               part-of, so the two are genuinely different views.
  spec docs    each task that carries `<!-- BEGIN SLICES -->` markers and has
               children gets its direct slices rolled up in place -- status, and
               the one-line outcome of each finished slice. This is fold-back
               done as derivation: a completed ticket's outcome shows in its
               spec with no manual copying, so nothing can drift.

revisit/ stays in the live index on purpose. Its whole value is being seen
before someone re-researches a problem it already settled; buried in an archive
nobody reads it, which defeats the category.

Everything between the BEGIN/END markers is owned by this script and rewritten
wholesale. Everything outside them -- retrospectives, why a decision was made,
what a session found -- is hand-written and never touched. That narrative is the
part of a board worth keeping; the per-task lines are the part worth generating.

`--check` rewrites nothing and exits 1 if either index is stale, for use in CI
or as a triage gate.

Imports the folder mapping from validate_board.py rather than restating it, so
the two can never disagree about where a task belongs. Standard library only.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from validate_board import (
    blocker_ids,
    collect_tasks,
    derive_folder,
    parse_frontmatter,
    part_of_id,
    task_kind,
)

BEGIN = "<!-- BEGIN GENERATED INDEX -->"
END = "<!-- END GENERATED INDEX -->"

# A task doc opts into an in-place slice rollup by carrying these markers.
SLICES_BEGIN = "<!-- BEGIN SLICES -->"
SLICES_END = "<!-- END SLICES -->"

GENERATED_NOTE = "*Generated by `scripts/generate_index.py` — do not edit by hand.*"

# Still in play. Rendered into README.md, grouped by folder then category.
LIVE_GROUPS: tuple[tuple[str, str, str], ...] = (
    ("", "Active", "Actionable now — no external gate."),
    (
        "manual-blocked",
        "Manual-blocked",
        "Waiting on a person to perform an action an agent cannot: provision, "
        "deploy, install, run against a live environment, or supply material.",
    ),
    (
        "owner-deferred",
        "Owner-deferred",
        "Waiting on a product, founder, legal, or vendor decision.",
    ),
    (
        "task-blocked",
        "Task-blocked",
        "Waiting on another task on this board, not on a person. Clears itself "
        "when the blocker reaches done.",
    ),
    (
        "revisit",
        "Revisit",
        "Done and working, with declined upgrade paths on record. Not a backlog — "
        "check the stated condition changed before picking one up.",
    ),
)

# History. Rendered into ARCHIVE.md, grouped by month.
ARCHIVE_GROUPS: tuple[tuple[str, str], ...] = (
    ("completed", "Completed"),
    ("superseded", "Superseded"),
)

# One source for the split. Deriving it from ARCHIVE_GROUPS rather than writing
# the set out again means a folder cannot be listed as live and archived at once,
# and cannot be silently dropped from both.
ARCHIVE_FOLDERS = frozenset(folder for folder, _ in ARCHIVE_GROUPS)

ARCHIVE_NAME = "ARCHIVE.md"

ARCHIVE_SCAFFOLD = f"""# Archive

Completed and superseded tasks, grouped by the month they closed. Kept for
provenance: read one before re-researching a problem it already covers.

Live work is indexed in [README.md](README.md).

{BEGIN}
{END}
"""

TREE_NAME = "TREE.md"

TREE_SCAFFOLD = f"""# Composition tree

Specs and the tickets and subtickets that compose them, nested by `part-of`
regardless of status. Where [README.md](README.md) groups by what a task is
waiting on, this groups by what it is a piece of.

{BEGIN}
{END}
"""


def load_tasks(board: Path) -> list[dict]:
    """Read every task, then derive its folder.

    Two passes, because blocked-by derivation depends on other tasks' statuses:
    a task's bucket is not knowable from its own frontmatter alone.
    """
    loaded: list[dict] = []
    for path in collect_tasks(board):
        front, _ = parse_frontmatter(path.read_text(encoding="utf-8"))
        if not front:
            continue
        front = dict(front)
        front["_path"] = path.relative_to(board).as_posix()
        loaded.append(front)

    resolved_ids = frozenset(
        str(front["id"])
        for front in loaded
        if front.get("id") and front.get("status") == "done"
    )
    for front in loaded:
        front["_folder"] = derive_folder(front, resolved_ids)
    return loaded


def entry_line(task: dict) -> str:
    """One flat-view row. The composition breadcrumb makes this the audit view:
    every ticket shows what it is part of, so the tree is legible without nesting.
    """
    title = str(task.get("title") or task.get("id"))
    priority = str(task.get("priority") or "?")
    status = str(task.get("status") or "?")
    tag = "`[spec]` " if task_kind(task) == "spec" else ""

    # Precedence matches how a reader scans: a supersede redirect dominates;
    # otherwise show composition (part-of), then a blocker, then lineage.
    suffix = ""
    if task.get("parent"):
        suffix = f" ↳ from `{task['parent']}`"
    part_of = part_of_id(task)
    if part_of:
        suffix = f" ⊂ part of `{part_of}`"
    blockers = blocker_ids(task)
    if blockers:
        suffix = " ⇠ blocked by " + ", ".join(f"`{b}`" for b in blockers)
    if task.get("superseded-by"):
        suffix = f" → `{task['superseded-by']}`"
    return f"- {tag}[{title}]({task['_path']}) — `{status}`, {priority} priority{suffix}"


def render_live(tasks: list[dict]) -> str:
    live = [t for t in tasks if t["_folder"] not in ARCHIVE_FOLDERS]
    archived = len(tasks) - len(live)

    lines: list[str] = [BEGIN, "", f"*{len(live)} live task(s). {GENERATED_NOTE[1:]}", ""]

    for folder, heading, blurb in LIVE_GROUPS:
        group = [task for task in live if task["_folder"] == folder]
        if not group:
            continue
        lines += [f"### {heading} ({len(group)})", "", blurb, ""]

        by_category: dict[str, list[dict]] = {}
        for task in group:
            by_category.setdefault(str(task.get("category") or "uncategorized"), []).append(task)

        for category in sorted(by_category):
            lines += [f"**{category}**", ""]
            for task in sorted(by_category[category], key=lambda t: str(t.get("id"))):
                lines.append(entry_line(task))
            lines.append("")

    if archived:
        lines += [
            f"### Archived ({archived})",
            "",
            f"Completed and superseded tasks are indexed in [{ARCHIVE_NAME}]({ARCHIVE_NAME}).",
            "",
        ]

    lines.append(END)
    return "\n".join(lines)


def render_archive(tasks: list[dict]) -> str:
    lines: list[str] = [BEGIN, ""]

    total = sum(1 for t in tasks if t["_folder"] in ARCHIVE_FOLDERS)
    lines += [f"*{total} archived task(s). {GENERATED_NOTE[1:]}", ""]

    for folder, heading in ARCHIVE_GROUPS:
        group = [task for task in tasks if task["_folder"] == folder]
        if not group:
            continue
        lines += [f"## {heading} ({len(group)})", ""]

        by_month: dict[str, list[dict]] = {}
        for task in group:
            stamp = str(task.get("updated") or "")
            by_month.setdefault(stamp[:7] or "undated", []).append(task)

        for month in sorted(by_month, reverse=True):
            entries = sorted(by_month[month], key=lambda t: str(t.get("id")))
            lines += [f"### {month} ({len(entries)})", ""]
            for task in entries:
                title = str(task.get("title") or task.get("id"))
                category = str(task.get("category") or "uncategorized")
                lines.append(f"- [{title}]({task['_path']}) — `{category}`")
                outcome = str(task.get("outcome") or "").strip()
                if outcome:
                    lines.append(f"  {outcome}")
            lines.append("")

    lines.append(END)
    return "\n".join(lines)


def _children_map(tasks: list[dict]) -> tuple[dict[str, dict], dict[str, list[dict]]]:
    """Return (id -> task, parent-id -> [child tasks]) over resolved part-of edges."""
    by_id = {str(t["id"]): t for t in tasks if t.get("id")}
    children: dict[str, list[dict]] = {}
    for task in tasks:
        parent = part_of_id(task)
        tid = str(task.get("id"))
        if parent and parent in by_id and parent != tid:
            children.setdefault(parent, []).append(task)
    return by_id, children


def _rel_link(from_path: str, to_path: str) -> str:
    """A link to to_path from a doc at from_path.

    Board folders are exactly one level deep, so a doc inside a folder reaches any
    other doc by going up once then descending; a doc at the root links directly.
    """
    return f"../{to_path}" if "/" in from_path else to_path


def render_tree(tasks: list[dict]) -> str:
    by_id, children = _children_map(tasks)
    child_ids = {str(t.get("id")) for kids in children.values() for t in kids}
    roots = sorted(
        (by_id[pid] for pid in children if pid not in child_ids and pid in by_id),
        key=lambda t: str(t.get("id")),
    )

    lines: list[str] = [BEGIN, ""]
    seen: set[str] = set()
    body: list[str] = []

    def emit(task: dict, depth: int) -> None:
        tid = str(task.get("id"))
        # Defensive only: part-of is single-valued, so a cycle is isolated and
        # unreachable from any root. This guards against a hang if that invariant
        # is ever broken (e.g. a hand-edited multi-parent part-of).
        if tid in seen:
            return
        seen.add(tid)
        tag = "`[spec]` " if task_kind(task) == "spec" else ""
        title = str(task.get("title") or tid)
        status = str(task.get("status") or "?")
        body.append(f"{'  ' * depth}- {tag}[{title}]({task['_path']}) — `{status}`")
        for child in sorted(children.get(tid, []), key=lambda t: str(t.get("id"))):
            emit(child, depth + 1)

    for root in roots:
        emit(root, depth=0)

    lines.append(f"*{len(seen)} task(s) across {len(roots)} tree(s). {GENERATED_NOTE[1:]}")
    lines.append("")
    lines += body
    lines += ["", END]
    return "\n".join(lines)


def render_slices(task: dict, children: list[dict]) -> str:
    """The in-place rollup for one parent task: its direct slices and outcomes."""
    lines = [SLICES_BEGIN, ""]
    if not children:
        lines += ["*No slices yet.*", ""]
    else:
        lines.append(f"*{len(children)} slice(s). {GENERATED_NOTE[1:]}")
        lines.append("")
        for child in sorted(children, key=lambda t: str(t.get("id"))):
            title = str(child.get("title") or child.get("id"))
            status = str(child.get("status") or "?")
            link = _rel_link(task["_path"], child["_path"])
            lines.append(f"- [{title}]({link}) — `{status}`")
            if child.get("status") == "done":
                outcome = str(child.get("outcome") or "").strip()
                if outcome:
                    lines.append(f"  {outcome}")
        lines.append("")
    lines.append(SLICES_END)
    return "\n".join(lines)


def splice(text: str, block: str, where: str, begin: str = BEGIN, end: str = END) -> str:
    start = text.find(begin)
    stop = text.find(end)
    if start == -1 or stop == -1 or stop < start:
        raise SystemExit(
            f"{where} has no generated block. Add these two markers where it "
            f"belongs:\n\n{begin}\n{end}"
        )
    return text[:start] + block + text[stop + len(end) :]


def write_lf(path: Path, text: str) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--board", type=Path, required=True, help="board root directory")
    parser.add_argument(
        "--check",
        action="store_true",
        help="report staleness without writing; exit 1 if either index would change",
    )
    args = parser.parse_args()

    board = args.board
    if not board.is_dir():
        print(f"not a directory: {board}", file=sys.stderr)
        return 2

    readme = board / "README.md"
    if not readme.is_file():
        print(f"no README.md on the board: {readme}", file=sys.stderr)
        return 2

    tasks = load_tasks(board)
    by_id, children = _children_map(tasks)
    archive = board / ARCHIVE_NAME
    tree = board / TREE_NAME

    # (path, current_text, rendered_block, begin_marker, end_marker)
    targets: list[tuple[Path, str, str, str, str]] = [
        (readme, readme.read_text(encoding="utf-8"), render_live(tasks), BEGIN, END)
    ]

    archived_any = any(task["_folder"] in ARCHIVE_FOLDERS for task in tasks)
    if archived_any or archive.is_file():
        current_archive = (
            archive.read_text(encoding="utf-8") if archive.is_file() else ARCHIVE_SCAFFOLD
        )
        targets.append((archive, current_archive, render_archive(tasks), BEGIN, END))

    # The composition view exists only when there is composition to show.
    if children or tree.is_file():
        current_tree = tree.read_text(encoding="utf-8") if tree.is_file() else TREE_SCAFFOLD
        targets.append((tree, current_tree, render_tree(tasks), BEGIN, END))

    # In-place slice rollups: any task doc that opted in by carrying the markers.
    for task in tasks:
        doc = board / task["_path"]
        current_doc = doc.read_text(encoding="utf-8")
        if SLICES_BEGIN not in current_doc:
            continue
        block = render_slices(task, children.get(str(task.get("id")), []))
        targets.append((doc, current_doc, block, SLICES_BEGIN, SLICES_END))

    stale: list[Path] = []
    for path, current, block, begin, end in targets:
        updated = splice(current, block, path.name, begin, end)
        if current != updated:
            stale.append(path)
            if not args.check:
                write_lf(path, updated)

    if args.check:
        if stale:
            for path in stale:
                print(f"STALE: {path} does not match the board")
            print("Run without --check to regenerate.")
            return 1
        print(f"OK: {len(targets)} generated region(s) match the board")
        return 0

    if stale:
        for path in stale:
            print(f"Regenerated {path}")
    else:
        print("OK: generated regions already match the board")
    return 0


if __name__ == "__main__":
    sys.exit(main())
